services:
  my_app:
    build: .
    env_file:
      - .env
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: postgresql+psycopg://postgres:postgres@db:5432/image-relevance
    depends_on:
      db:
        condition: service_healthy
  
  db:
    image: pgvector/pgvector:pg16
    environment:
      POSTGRES_DB: image-relevance
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d image-relevance"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s